# API test request for the endpoint /api/device/status
# 

POST https://staging.datahub.luftdaten.at/api/v1/devices/data/ HTTP/1.1
content-type: application/json

{
    "station": {
        "time": "2025-01-07T11:23:23.439Z",
        "device": "string",
        "firmware": "string",
        "model": 0,
        "apikey": "initialStationInfoTest",
        
        "sensor_list": [
            {
                "model_id": 1,
                "dimension_list": [1, 2, 3]
            }
        ]
    },
    "sensors": {}
}