# Generated by Django 5.1.2 on 2024-12-10 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_alter_campaign_id_alter_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='campaign.organization'),
        ),
    ]
