# Generated by Django 5.1.2 on 2024-12-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_organizationinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationinvitation',
            name='expiring_date',
            field=models.DateField(null=True),
        ),
    ]
