# API test request for initial device registration (via status endpoint)
# 

POST http://localhost/api/v1/devices/status/ HTTP/1.1
content-type: application/json

{
  "device": {
    "time": "2025-01-07T11:23:23.439Z",
    "device": "initial_station_info",
    "firmware": "string",
    "model": 4,
    "apikey": "initial_station_info_test",
    "sensor_list": [
      { "model_id": 1, "dimension_list": [1, 2, 3] }
    ]
  },
  "status_list": [
    { "time": "2025-01-07T11:23:23.439Z", "level": 1, "message": "initial_station_info" }
  ]
}