# API test request for the endpoint /api/v1/devices/data
# Request body: device, workshop, sensors (see API docs)

POST http://localhost/api/v1/devices/data/ HTTP/1.1
content-type: application/json

{
  "device": {
    "time": "2024-04-29T08:25:20.766Z",
    "id": "string",
    "firmware": "1.0",
    "model": 1,
    "apikey": "your-api-key"
  },
  "workshop": {
    "id": "workshop-name",
    "participant": "participant-uuid",
    "mode": "walking"
  },
  "sensors": {
    "1": {
      "type": 1,
      "data": {
        "2": 5.0,
        "3": 6.0,
        "5": 7.0,
        "6": 0.67,
        "7": 20.0
      }
    }
  }
}