# API test request for the endpoint /api/device/data/add
# 

POST http://localhost/api/device/data/add/ HTTP/1.1
content-type: application/json

[
  {
    "time": "2024-04-29T08:25:20.766Z",
    "device": "string",
    "lat": 0,
    "lon": 0,
    "location_precision": 0,
    "mode": "string",
    "measurements": [
      {
        "sensor": "string",
        "pm1": 0,
        "pm25": 0,
        "pm10": 0,
        "temperature": 0,
        "humidity": 0,
        "voc_index": 0,
        "nox_index": 0,
        "co2": 0,
        "o3": 0,
        "iaq_index": 0,
        "iaq_acc": 0,
        "iaq_static": 0,
        "pressure": 0
      }
    ]
  }
]