services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: gunicorn main.wsgi -b 0.0.0.0:8000
    volumes:
      - ./code:/code
    env_file:
      - .env
    depends_on:
     - db  
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  nginx:
    build: ./nginx
    volumes:
      - ./code/staticfiles:/home/app/web/staticfiles
#      - static_volume:/home/app/web/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web      
volumes:
  postgres_data: