services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app
    env_file:
      - .env
    depends_on:
     - db  
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  nginx:
    build: ./nginx
    volumes:
      - ./app/staticfiles:/home/app/web/staticfiles
#      - static_volume:/home/app/web/staticfiles
    ports:
      - "80:80"
    depends_on:
      - app      
volumes:
  postgres_data: