services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: gunicorn main.wsgi -b 0.0.0.0:8000
    volumes:
      - ./code:/code
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-a9s=^powdnf6s1*nh)2vnznh+8uj_7tvsd^_so-jmlgkvokn7*"
      - "DJANGO_DEBUG=True"
      - "DJANGO_SECURE_SSL_REDIRECT=False"
      - "DJANGO_SECURE_HSTS_SECONDS=0"
      - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False"
      - "DJANGO_SECURE_HSTS_PRELOAD=False"
      - "DJANGO_SESSION_COOKIE_SECURE=False"
      - "DJANGO_CSRF_COOKIE_SECURE=False"
    depends_on:
     - db  
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  nginx:
    build: ./nginx
    volumes:
      - ./code/staticfiles:/home/app/web/staticfiles
#      - static_volume:/home/app/web/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web      
volumes:
  postgres_data: