services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./code:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
    # docker-compose exec web python -c "import secrets; print(secrets.token_urlsafe(38))"
      - "DJANGO_SECRET_KEY=x"
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data: