# Generated by Django 6.0.8 on 2026-08-08 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='municipalityheatprofile',
            new_name='context_mun_referen_b06c0a_idx',
            old_name='context_mun_referen_idx',
        ),
    ]
