
POST http://localhost/api/workshop/data/add HTTP/1.1
content-type: application/json

{
    "time": "2019-01-01T00:00:00+00:00",
    "pm1": 10,
    "pm25": 20,
    "pm10": 30,
    "temperature": 20,
    "humidity": 50,
    "voc": 100,
    "nox": 200,
    "device": {
        "name": "B040",
        "model": "Air aRound v1"
    },
    "workshop": "i7847g",
    "location": {
        "lat": 51.509865,
        "lon": -0.118092,
        "precision": 10
    }
}