from django.urls import path
from .views import (
    AirStationsOverviewView,
    DeviceDeleteView,
    DeviceDetailView,
    DeviceEditView,
    DeviceListView,
    DeviceLogLevelUpdateView,
    DeviceLogsCSVView,
    DeviceMoveMeasurementsView,
    DeviceMyView,
    DeviceNotesUpdateView,
    DeviceApikeyUpdateView,
    DeviceDataDownloadView,
    DeviceDataView,
    DeviceMeasurementsView,
    MeasurementDeleteView,
    SensorDetailView,
    calibrationView,
)

urlpatterns = [
    path('', DeviceListView.as_view(), name='devices-list'),
    path('air-stations/', AirStationsOverviewView.as_view(), name='air-stations-overview'),
    path('calibration/', calibrationView, name='calibration'),
    path('my/', DeviceMyView.as_view(), name='devices-my'),
    path('sensors/<int:pk>/', SensorDetailView.as_view(), name='sensor-detail'),
    path('<str:pk>/', DeviceDetailView.as_view(), name='device-detail'),
    path('<str:pk>/move-measurements/', DeviceMoveMeasurementsView.as_view(), name='device-move-measurements'),
    path('<str:pk>/data/download/', DeviceDataDownloadView.as_view(), name='device-data-download'),
    path('<str:pk>/data/', DeviceDataView.as_view(), name='device-data'),
    path('<str:pk>/measurements/', DeviceMeasurementsView.as_view(), name='device-measurements'),
    path('<str:pk>/measurements/<int:measurement_pk>/delete/', MeasurementDeleteView.as_view(), name='measurement-delete'),
    path('<str:pk>/delete/', DeviceDeleteView.as_view(), name='device-delete'),
    path('<str:pk>/edit/', DeviceEditView.as_view(), name='device-edit'),
    path('<str:pk>/edit-notes/', DeviceNotesUpdateView.as_view(), name='device-edit-notes'),
    path('<str:pk>/edit-apikey/', DeviceApikeyUpdateView.as_view(), name='device-edit-apikey'),
    path('<str:pk>/log-level/', DeviceLogLevelUpdateView.as_view(), name='device-log-level'),
    path('<str:pk>/logs.csv', DeviceLogsCSVView.as_view(), name='device-logs-csv'),
]