# Generated by Django 4.2.6 on 2024-03-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airqualityrecord',
            name='workshop',
            field=models.ManyToManyField(related_name='workshop', to='workshops.workshop'),
        ),
    ]
