# Generated by Django 4.2.6 on 2024-03-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_device_board_id_alter_device_btmac_address_and_more'),
        ('api', '0002_airqualityrecord_workshop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airqualityrecord',
            name='device',
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='humidity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='nox',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='pm1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='pm10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='pm25',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='voc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='precision',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airqualityrecord',
            name='device',
            field=models.ManyToManyField(related_name='device', to='devices.device'),
        ),
    ]
