# Generated by Django 4.2.6 on 2024-03-06 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_alter_workshop_description'),
        ('devices', '0003_alter_device_board_id_alter_device_btmac_address_and_more'),
        ('api', '0003_remove_airqualityrecord_device_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airqualityrecord',
            name='device',
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.location'),
        ),
        migrations.RemoveField(
            model_name='airqualityrecord',
            name='workshop',
        ),
        migrations.AddField(
            model_name='airqualityrecord',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.device'),
        ),
        migrations.AddField(
            model_name='airqualityrecord',
            name='workshop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workshops.workshop'),
        ),
    ]
