# Generated by Django 4.2.11 on 2024-03-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_airqualityrecord_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airqualityrecord',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='nox',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='pm1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='pm10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='pm25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='voc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
