# Generated by Django 4.2.11 on 2024-03-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_airqualityrecord_humidity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airqualityrecord',
            name='location_precision',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
