# Generated by Django 4.2.11 on 2024-03-25 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_airqualityrecord_location_precision'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobilityMode',
            fields=[
                ('id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='airqualityrecord',
            name='mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.mobilitymode'),
        ),
    ]
