# Generated by Django 4.2.11 on 2024-03-25 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_airqualityrecord_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobilitymode',
            old_name='id',
            new_name='name',
        ),
    ]
