# Generated by Django 4.2.11 on 2024-03-27 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0005_participant'),
        ('api', '0010_rename_id_mobilitymode_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='airqualityrecord',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workshops.participant'),
        ),
    ]
