# Generated by Django 4.2.11 on 2024-03-27 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0008_alter_participant_workshop'),
        ('devices', '0004_devicemodel_device_model'),
        ('api', '0011_airqualityrecord_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airqualityrecord',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.device'),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.mobilitymode'),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshops.participant'),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='workshop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshops.workshop'),
        ),
    ]
