# Generated by Django 4.2.11 on 2024-04-26 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0014_participant_device'),
        ('api', '0012_alter_airqualityrecord_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airqualityrecord',
            name='co2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airqualityrecord',
            name='iaq_acc',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airqualityrecord',
            name='iaq_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airqualityrecord',
            name='iaq_static',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airqualityrecord',
            name='o3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airqualityrecord',
            name='pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshops.workshop'),
        ),
    ]
