# Generated by Django 4.2.11 on 2024-04-29 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0014_participant_device'),
        ('api', '0013_airqualityrecord_co2_airqualityrecord_iaq_acc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airqualityrecord',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshops.participant'),
        ),
    ]
