# Generated by Django 4.2.11 on 2024-04-29 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
        ('workshops', '0014_participant_device'),
        ('devices', '0011_sensor'),
        ('api', '0014_alter_airqualityrecord_participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirQualityDatapoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('location_precision', models.FloatField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign.campaign')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.device')),
                ('mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.mobilitymode')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshops.participant')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshops.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm1', models.FloatField(blank=True, help_text='Particulate matter 1 microns', null=True)),
                ('pm25', models.FloatField(blank=True, help_text='Particulate matter 2.5 microns', null=True)),
                ('pm10', models.FloatField(blank=True, help_text='Particulate matter 10 microns', null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('voc_index', models.FloatField(blank=True, help_text='Volatile organic compound index', null=True)),
                ('nox_index', models.FloatField(blank=True, help_text='Nitrogen oxides index', null=True)),
                ('co2', models.FloatField(blank=True, help_text='Carbondioxid', null=True)),
                ('o3', models.FloatField(blank=True, help_text='Ground-level Ozone', null=True)),
                ('iaq_index', models.FloatField(blank=True, null=True)),
                ('iaq_acc', models.SmallIntegerField(blank=True, null=True)),
                ('iaq_static', models.FloatField(blank=True, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('datapoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.airqualitydatapoint')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.sensor')),
            ],
        ),
    ]
