# Generated by Django 4.2.11 on 2024-05-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_airqualitydatapoint_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
