# Generated by Django 4.2.11 on 2024-05-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_measurement_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airqualitydatapoint',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
