# Generated by Django 4.2.6 on 2024-03-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('name', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('board_id', models.CharField(max_length=12)),
                ('btmac_address', models.CharField(max_length=12)),
            ],
        ),
    ]
