# Generated by Django 4.2.11 on 2024-05-23 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(blank=True, default=None, max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=4)),
                ('btmac_address', models.CharField(blank=True, max_length=12, null=True)),
                ('sensor_sen5x', models.CharField(blank=True, max_length=255, null=True)),
                ('sensor_bme280', models.CharField(blank=True, max_length=255, null=True)),
                ('sensor_bme680', models.CharField(blank=True, max_length=255, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time_received', models.DateTimeField()),
                ('battery_voltage', models.FloatField(blank=True, null=True)),
                ('battery_soc', models.FloatField(blank=True, null=True)),
                ('sensors', models.JSONField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.devicemodel'),
        ),
    ]
