# Generated by Django 4.2.11 on 2024-05-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
