# Generated by Django 4.2.11 on 2024-04-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_alter_device_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firmwareversion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
