# Generated by Django 4.2.11 on 2024-04-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_devicemodel_description_firmwareversion_description'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE api_airqualityrecord DROP CONSTRAINT api_airqualityrecord_device_id_0dead150_fk_devices_device_name;",
            "ALTER TABLE api_airqualityrecord ADD CONSTRAINT api_airqualityrecord_device_id_0dead150_fk_devices_device_new FOREIGN KEY (device_id) REFERENCES devices_device (new_id_column) DEFERRABLE INITIALLY DEFERRED"
        ),
        migrations.RunSQL(
            "ALTER TABLE workshops_participant DROP CONSTRAINT workshops_participant_device_id_e2b87eaf_fk_devices_device_name;",
            "ALTER TABLE workshops_participant ADD CONSTRAINT workshops_participant_device_id_e2b87eaf_fk_devices_device_new FOREIGN KEY (device_id) REFERENCES devices_device (new_id_column) DEFERRABLE INITIALLY DEFERRED"
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AddField(
            model_name='device',
            name='id',
            field=models.AutoField(primary_key=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='board_id',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),

    ]
