# Generated by Django 4.2.11 on 2024-04-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_device_id_alter_device_board_id_alter_device_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=4),
        ),
    ]
