# Generated by Django 4.2.11 on 2024-05-12 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_sensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time_received', models.DateTimeField()),
                ('status', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='firmware_version',
        ),
        migrations.DeleteModel(
            name='FirmwareVersion',
        ),
        migrations.AddField(
            model_name='devicestatus',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device'),
        ),
    ]
