# Generated by Django 5.1.2 on 2024-12-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_alter_sensor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='api_key',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
