# Generated by Django 5.1.2 on 2025-01-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_remove_sensor_api_key_device_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='firmware',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
