# Generated by Django 5.1.2 on 2025-01-03 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_alter_organizationinvitation_expiring_date'),
        ('devices', '0009_device_current_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='current_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_devices', to='campaign.organization'),
        ),
    ]
