# Generated by Django 5.1.2 on 2025-01-08 15:17

import django.db.models.deletion
from django.db import migrations, models


def set_invalid_foreign_keys_to_null(apps, schema_editor):
    Device = apps.get_model('devices', 'Device')
    Organization = apps.get_model('organizations', 'Organization')
    for device in Device.objects.all():
        if not Organization.objects.filter(id=device.current_organization_id).exists():
            device.current_organization = None
            device.save()

class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_remove_devicestatus_sensors_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(set_invalid_foreign_keys_to_null),
        migrations.AlterField(
            model_name='device',
            name='current_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_devices', to='organizations.organization'),
        ),
    ]
