# Generated by Django 5.1.2 on 2025-01-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_device_current_user_measurement_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestatus',
            name='sensor_list',
            field=models.JSONField(null=True),
        ),
    ]
