# Generated by Django 5.1.2 on 2025-01-27 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0009_remove_organization_owner_remove_organization_users_and_more'),
        ('devices', '0013_device_current_user_measurement_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='current_campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_devices', to='campaign.campaign'),
        ),
    ]
