# Generated by Django 5.1.2 on 2025-01-29 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0014_device_current_campaign'),
        ('devices', '0014_devicestatus_sensor_list'),
    ]

    operations = [
    ]
