# Generated by Django 5.1.2 on 2025-01-29 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0009_remove_organization_owner_remove_organization_users_and_more'),
        ('devices', '0015_merge_20250129_0930'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='current_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_devices', to='campaign.campaign'),
        ),
        migrations.AlterField(
            model_name='device',
            name='current_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_devices', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='device',
            name='current_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_devices', to='campaign.room'),
        ),
        migrations.AlterField(
            model_name='device',
            name='current_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
