# Generated by Django 5.1.5 on 2025-01-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0016_alter_device_current_campaign_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, unique=True)),
                ('last_auto_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='auto_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
