# Generated by Django 5.1.5 on 2025-01-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0017_modelcounter_device_auto_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelcounter',
            name='id',
        ),
        migrations.AlterField(
            model_name='modelcounter',
            name='model',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
