# Generated by Django 5.1.5 on 2025-01-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0018_remove_modelcounter_id_alter_modelcounter_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelcounter',
            name='model',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
