# Generated by Django 5.2 on 2025-05-02 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0020_device_created_at'),
        ('workshops', '0009_alter_workshopimage_workshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='workshop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='workshops.workshop'),
        ),
    ]
