# Generated by Django 5.2 on 2025-05-05 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_airqualityrecord_device'),
        ('devices', '0021_measurement_workshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='api.location'),
        ),
    ]
