# Generated by Django 5.2 on 2025-05-05 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_airqualityrecord_device'),
        ('devices', '0022_measurement_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='api.mobilitymode'),
        ),
    ]
