# Generated by Django 5.2 on 2025-05-05 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0024_measurement_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='devices.device'),
        ),
    ]
