# Generated by Django 5.2 on 2025-05-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0025_alter_measurement_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='time_received',
            field=models.DateTimeField(null=True),
        ),
    ]
