# Generated by Django 5.2 on 2025-05-14 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0026_alter_measurement_time_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='calibration_mode',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='test_mode',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='device',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='devices.device'),
            preserve_default=False,
        ),
    ]
