# Generated by Django 5.1.2 on 2024-12-09 08:58

from django.db import migrations, models
from devices.models import Sensor


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('devices', '0004_alter_device_model_remove_device_sensor_bme280_and_more')
    ]
    # TODO: migrate data aswell
    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='sensor',
        ),
        migrations.AddField(
            model_name='measurement',
            name='sensor',
            field=models.ForeignKey(
                to='devices.Sensor',
                on_delete=models.CASCADE,
            ),
        ),
    ]
