# Generated by Django 5.1.2 on 2024-12-09 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_fk'),
        ('campaign', '0002_alter_campaign_id_alter_campaign_name_organization_and_more'),
        ('devices', '0005_alter_sensor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLogs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('level', models.IntegerField()),
                ('message', models.TextField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementNew',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time_received', models.DateTimeField()),
                ('time_measured', models.DateTimeField()),
                ('sensor_model', models.IntegerField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.room')),
            ],
        ),
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dimension', models.IntegerField()),
                ('value', models.FloatField()),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.measurementnew')),
            ],
        ),
    ]
