# Generated by Django 5.1.2 on 2024-12-20 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_devicelogs_id_alter_measurementnew_id_and_more'),
        ('campaign', '0008_alter_organizationinvitation_expiring_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementnew',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.room'),
        ),
    ]
