# Generated by Django 5.1.2 on 2025-01-03 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_measurementnew_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='values',
            name='measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='api.measurementnew'),
        ),
    ]
