# Generated by Django 5.1.2 on 2025-01-03 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_values_measurement'),
        ('campaign', '0008_alter_organizationinvitation_expiring_date'),
        ('devices', '0010_device_current_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementnew',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='devices.device'),
        ),
        migrations.AlterField(
            model_name='measurementnew',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='campaign.room'),
        ),
    ]
