# Generated by Django 5.1.2 on 2025-01-07 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_measurementnew_device_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='datapoint',
        ),
        migrations.RemoveField(
            model_name='devicelogs',
            name='device',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='measurementnew',
            name='device',
        ),
        migrations.RemoveField(
            model_name='measurementnew',
            name='room',
        ),
        migrations.RemoveField(
            model_name='values',
            name='measurement',
        ),
        migrations.DeleteModel(
            name='AirQualityDatapoint',
        ),
        migrations.DeleteModel(
            name='DeviceLogs',
        ),
        migrations.DeleteModel(
            name='Measurement',
        ),
        migrations.DeleteModel(
            name='MeasurementNew',
        ),
        migrations.DeleteModel(
            name='Values',
        ),
    ]
