# Generated by Django 5.2 on 2025-04-29 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
