# Generated by Django 5.2 on 2025-04-29 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_location'),
        ('workshops', '0008_workshopimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airqualityrecord',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air_quality_records', to='workshops.workshop'),
        ),
    ]
