# Generated by Django 5.2 on 2025-04-30 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_airqualityrecord_workshop'),
        ('devices', '0020_device_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airqualityrecord',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air_quality_records', to='devices.device'),
        ),
    ]
