# Generated by Django 5.2 on 2025-07-04 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_airqualityrecord_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='airqualityrecord',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air_quality_records', to='api.location'),
        ),
    ]
