# Generated by Django 5.2 on 2025-04-28 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiring_date', models.DateField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='workshops.workshop')),
            ],
            options={
                'unique_together': {('email', 'workshop')},
            },
        ),
    ]
