# Generated by Django 5.2 on 2025-04-28 08:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_workshopinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='users',
            field=models.ManyToManyField(related_name='workshops', to=settings.AUTH_USER_MODEL),
        ),
    ]
