# Generated by Django 5.2 on 2025-04-28 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_workshop_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='workshop_images/')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='workshops.workshop')),
            ],
        ),
    ]
