# Generated by Django 5.2 on 2025-04-29 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0006_workshopimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkshopImage',
        ),
    ]
