# Generated by Django 5.2 on 2025-04-29 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_location'),
        ('workshops', '0007_delete_workshopimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='workshop_images/')),
                ('time_created', models.DateTimeField(null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_images', to='api.location')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='workshops.workshop')),
            ],
        ),
    ]
