# Generated by Django 5.2 on 2025-04-29 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0008_workshopimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopimage',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_images', to='workshops.workshop'),
        ),
    ]
