# Generated by Django 5.2 on 2025-05-26 11:47

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0009_alter_workshopimage_workshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('radius', models.FloatField()),
                ('area', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('type', models.CharField()),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_spots', to='workshops.workshop')),
            ],
        ),
    ]
