# Generated by Django 5.2.9 on 2026-01-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0010_workshopspot'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='heat_hotspots_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
