# Generated by Django 4.2.11 on 2024-05-23 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('name', models.CharField(blank=True, editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('public', models.BooleanField(default=True)),
                ('mapbox_top_left_lat', models.FloatField(blank=True, null=True)),
                ('mapbox_top_left_lon', models.FloatField(blank=True, null=True)),
                ('mapbox_top_right_lat', models.FloatField(blank=True, null=True)),
                ('mapbox_top_right_lon', models.FloatField(blank=True, null=True)),
                ('mapbox_bottom_left_lat', models.FloatField(blank=True, null=True)),
                ('mapbox_bottom_left_lon', models.FloatField(blank=True, null=True)),
                ('mapbox_bottom_right_lat', models.FloatField(blank=True, null=True)),
                ('mapbox_bottom_right_lon', models.FloatField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_workshops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.device')),
                ('workshop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshops.workshop')),
            ],
        ),
    ]
