# Generated by Django 4.2.6 on 2024-03-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='id',
            field=models.CharField(blank=True, editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
