# Generated by Django 4.2.11 on 2024-03-27 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0004_rename_id_workshop_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('workshop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workshops.workshop')),
            ],
        ),
    ]
