# Generated by Django 4.2.11 on 2024-03-27 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0007_remove_participant_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='workshop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshops.workshop'),
        ),
    ]
