# Generated by Django 4.2.11 on 2024-03-27 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_devicemodel_device_model'),
        ('workshops', '0008_alter_participant_workshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.device'),
        ),
    ]
