# Generated by Django 4.2.11 on 2024-03-28 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0010_workshop_mapbox_bottom_left_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop',
            old_name='mapbox_topr_ight_lat',
            new_name='mapbox_top_right_lat',
        ),
    ]
