# Generated by Django 4.2.11 on 2024-03-28 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshops', '0011_rename_mapbox_topr_ight_lat_workshop_mapbox_top_right_lat'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_workshops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workshop',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
