# Generated by Django 4.2.11 on 2024-04-02 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0012_workshop_owner_workshop_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='device',
        ),
    ]
